# version: "3.8"
#ipconfig getifaddr en0

services:
  superset:
    build: .
    container_name: custom_superset
    ports:
      - "8088:8088"
    environment:
      - SUPERSET_SECRET_KEY="flOZv9DVD3AZ-XyGPClEjvDiYfm6Pigiy6DTrTWsuLx0hJk6xxzp4aB36J5l8GC0l2DgjFZyG2M2Se_HJdFFXg"
      - SUPERSET_HOME=/app/superset_home
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PYTHONPATH=/app/pythonpath
      - DATABASE_URL=postgresql+psycopg2://superset:superset@superset_db:5432/superset
    depends_on:
      - redis
      - db
    volumes:
      - ./superset/config:/app/pythonpath
      - ./superset/superset_home:/app/superset_home
      - ./superset/assets:/app/superset/static/assets/images
      - ./data/preart.db:/app/data/preart.db
    command: >
      /bin/sh -c "
      superset db upgrade &&
      superset fab create-admin --username admin --firstname Superset --lastname Admin --email admin@superset.com --password admin && 
      superset init &&
      superset run -h 0.0.0.0 -p 8088"

  db:
    image: postgres:15
    container_name: superset_db
    environment:
      POSTGRES_DB: superset
      POSTGRES_USER: superset
      POSTGRES_PASSWORD: superset
    volumes:
      - ./postgres:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: superset_redis
    volumes:
      - "./redis/data:/data"
    ports:
      - "6379:6379"

  nginx:
    image: nginx:alpine
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - superset
# volumes:
#   pgdata:
